### ISSUE TITLE
使用面板后，面板上所有的数字全部为空白

### ISSUE THREAD

**Issue by Rakau** [MetaCubeX/Yacd-meta#22]

**Comment by Rakau** [comment]
![Screenshot_2023-04-12-09-50-04-952_com chrome beta](https://user-images.githubusercontent.com/33389179/231326767-52b457e9-20b1-448a-a31f-19d007c0367a.jpg)

**Comment by Astlm** [comment]
那是系统字体的问题

**Comment by Rakau** [comment]
> 那是系统字体的问题

前几个yacd版本没问题

**Comment by Astlm** [comment]
> > 那是系统字体的问题
> 
> 前几个yacd版本没问题

那不清楚 反正更换字体可以解决这个问题

**Comment by Rakau** [comment]
> @Astlm ctrl+f5 刷新，如果你的系统没有安装 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Source Han Sans SC","Segoe UI Emoji", "Segoe UI Symbol", "PingFang SC", "Microsoft YaHei" ,'\5fae\8f6f\96c5\9ed1', Arial, 的其中任何一种字体，才会有这种情况

手机没有ctrl+f5

**Comment by xishang0128** [comment]
@Rakau 清除缓存重启浏览器

**Comment by xishang0128** [comment]
@Rakau 使用的什么浏览器,我使用chrome/safari一切正常

**Comment by Rakau** [comment]
> @Rakau 使用的什么浏览器,我使用chrome/safari一切正常

chrome和小米自带浏览器都这样，M核搭配的是https://github.com/CHIZI-0618/box4magisk

**Comment by Rakau** [comment]
> 我是把「/assets/index-xxxxx.css」里面的「"_Twemoji Mozilla",」删除就正常了，你可以尝试下

感谢，成功解决

**Comment by wenhelinlu** [comment]
> 我是把「/assets/index-xxxxx.css」里面的「"_Twemoji Mozilla",」删除就正常了，你可以尝试下

成功解决👍
