### ISSUE TITLE
GLOBAL 组中有 GLOBAL 可选

### ISSUE THREAD

**Issue by tdjnodj** [MetaCubeX/Yacd-meta#34]
正常情况下，GLOBAL 组中不会有 GLOBAL 可供选择。但是在 yacd 中，GLOBAL 组却多出了 GLOBAL 可选：

![](https://raw.githubusercontent.com/tdjnodj/picture_bed/main/issue/2023050101.png)

`curl http://127.0.0.1:9090/proxies/` 后，发现 GLOBAL 组中并没有自己。使用其他面板，也是没有自己。

在 yacd 中选中这个多出来的 GLOBAL，图标显示切换了节点，但刷新后又恢复原样。

**Comment by Larvan2** [comment]
这个属于[上游行为](https://github.com/haishanh/yacd)

**Comment by tdjnodj** [comment]
上游没有这个 bug

**Comment by tdjnodj** [comment]
感谢开发者
