### ISSUE TITLE
需求请求：读取ptr记录，在连接界面添加客户端名称列；活动下方IP地址变更为客户端名称

### ISSUE THREAD

**Issue by yyysuo** [MetaCubeX/Yacd-meta#48]
感谢大佬：
![image](https://github.com/MetaCubeX/Yacd-meta/assets/10081071/a15fad00-fb33-4eb2-95bc-c5e53d24cddd)

可否读取主路由本身的ptr记录，把内网ip地址显示为客户端名称，同时添加客户端名称列，这样比较方便看系统里面哪些设备在跑流量，对于没有ptr记录的设备，可否在系统指定目录自己维护自定义显示的设备名称，如果有ptr记录的话，优选显示自定义的设备名称。非常感谢。

![image](https://github.com/MetaCubeX/Yacd-meta/assets/10081071/1a95badb-6fd3-42da-9c04-252461dea1eb)

**Comment by kunish** [comment]
前端是做不到这个事情的，后端如果在接口里有返回客户端名称的话可以实现

**Comment by nb5p** [comment]
前端可以让用户输入，再跟据输入内容把IP替换为主机名
