### ISSUE TITLE
手机版本连接页面页面，滚动条重复

### ISSUE THREAD

**Issue by pengfujin-momo** [MetaCubeX/Yacd-meta#56]
发现不只在手机版本有，PC版本的页面缩小一下横纵比列也会出现。

![image](https://github.com/MetaCubeX/Yacd-meta/assets/57943069/e6424fda-af9e-4b30-a5b2-f10f8d518795)

![image](https://github.com/MetaCubeX/Yacd-meta/assets/57943069/4336906a-ceb0-4604-b7ff-d8d91cd82111)

**Comment by xishang0128** [comment]
@pengfujin-momo 一个是web的滚动条,浏览器提供的,一个是表的,挺正常的)
