### ISSUE TITLE
希望能添加在线配置规则的功能

### ISSUE THREAD

**Issue by badboy-tian** [MetaCubeX/Yacd-meta#70]
如题，需要自定义规则的时候，需要scp到config.ymal文件里面去新增规则，很麻烦，。，希望在规则里面添加自定义规则 ，谢谢 非常需要哦

![image](https://github.com/MetaCubeX/Yacd-meta/assets/2835129/6df496a9-6165-4788-8089-08fcd6e9e396)

**Comment by badboy-tian** [comment]
添加自定义规则， 比如某个网址没有被命中规则  可以手动添加下

**Comment by xishang0128** [comment]
@badboy-tian yacd只是一个拿来"看"和"选"的网页,不是启动器,所以做不到

**Comment by xishang0128** [comment]
@badboy-tian 内核也并不提供相应api,谁启动的clash,谁管理的配置文件,找谁

**Comment by badboy-tian** [comment]
好吧
