### ISSUE TITLE
为什么URL Test是可以手动选择的？

### ISSUE THREAD

**Issue by lixin-wei** [MetaCubeX/Yacd-meta#72]
如图，url-test类型的group，竟然可以点击，而且会真的发PUT请求取修改，这是为什么呢？url-test不应该不能选择吗？
<img width="1350" alt="image" src="https://github.com/MetaCubeX/Yacd-meta/assets/19600697/84c6159b-1da5-4ebe-b0a2-cc20fbf9004f">

**Comment by Zephyruso** [comment]
feature url-test支持指定

**Comment by lixin-wei** [comment]
感谢回复，那我通过点击指定后，怎么让他恢复自动选择呢？点那个测速按钮好像没用

**Comment by lixin-wei** [comment]
不对呀，我翻了下代码，他是会检查是不是selector类型的。为啥没报错呢奇怪

https://github.com/MetaCubeX/Clash.Meta/blob/65071ea7d16724ef3262366f0c0877b4a73d815b/hub/route/proxies.go#L85-L90

**Comment by lixin-wei** [comment]
已经解决了：https://github.com/MetaCubeX/Clash.Meta/issues/693
